tcpserver : tcpserver.c
	gcc tcpserver.c -o tcpserver

tcpclient : tcpclient.c
	gcc tcpclient.c -o tcpclient

udpserver : udpserver.c
	gcc udpserver.c -o udpserver

udpclient : udpclient.c
	gcc udpclient.c -o udpclient